"""
Advanced AutoGen CSV Analysis System
Multi-agent system with specialized agents for different tasks.
"""

import os
import sys
import pandas as pd
import json
from pathlib import Path
import autogen

# ------------------------ Configuration ------------------------ #
config_list = {
    'model': 'minimax-m2:cloud',
    'base_url': 'http://localhost:11434/v1',
    'api_key': 'ollama',
    'api_type': 'openai',
}

llm_config = {
    "config_list": [config_list],
    "temperature": 0.3,  # Lower temperature for more precise coding
    "max_tokens": 2000,
}

CSV_FILE = 'Input/input.csv'
REPORT_FILE = 's.md'
OUTPUT_DIR = 'generated_code'

# Create output directory
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ------------------------ Data Loader ------------------------ #
def load_data_context():
    """Load CSV data and metadata for context."""
    try:
        df = pd.read_csv(CSV_FILE)
        report_content = ""
        if os.path.exists(REPORT_FILE):
            with open(REPORT_FILE, 'r') as f:
                report_content = f.read()

        # Create a summary of the data
        data_summary = {
            'file': CSV_FILE,
            'shape': df.shape,
            'columns': df.columns.tolist(),
            'dtypes': df.dtypes.astype(str).to_dict(),
            'numeric_columns': df.select_dtypes(include=['number']).columns.tolist(),
            'categorical_columns': df.select_dtypes(include=['object', 'category']).columns.tolist(),
            'sample_data': df.head(3).to_dict('records'),
            'missing_values': df.isnull().sum().to_dict(),
        }

        return df, report_content, data_summary

    except Exception as e:
        print(f"[ERROR] Failed to load data: {e}")
        return None, None, None


# ------------------------ Specialized Agents ------------------------ #

# 1. Coder Agent - Generates and executes code
coder_agent = autogen.AssistantAgent(
    name="CoderAgent",
    llm_config=llm_config,
    system_message="""You are an expert Python data analyst and software engineer.

CAPABILITIES:
- Write production-quality Python code using pandas, numpy, matplotlib, seaborn, etc.
- Analyze CSV data and generate insights
- Create visualizations and statistical summaries
- Filter, transform, and manipulate data
- Export results in various formats

WORKFLOW:
1. Understand the user request
2. Review the CSV data context provided
3. Generate well-commented, executable Python code
4. Save code to file in OUTPUT_DIR
5. Execute the code safely
6. Provide clear explanation of results

CONSTRAINTS:
- Always load data from 'Input/input.csv'
- Use pandas for data manipulation
- Add clear comments and docstrings
- Handle errors gracefully
- Save outputs with descriptive names
- Use matplotlib/seaborn for visualizations

When you receive a request, generate code that directly addresses it."""
)

# 2. Data Analyst Agent - Provides insights and analysis strategy
analyst_agent = autogen.AssistantAgent(
    name="DataAnalyst",
    llm_config=llm_config,
    system_message="""You are a senior data analyst.

ROLE:
- Understand business questions and translate them to data analysis tasks
- Recommend appropriate analysis methods
- Validate code generated by CoderAgent
- Provide insights and interpretations
- Suggest next steps for analysis

When reviewing code or results, provide:
1. Technical validation
2. Business interpretation
3. Recommendations for improvement
4. Suggested follow-up analyses"""
)

# 3. Code Reviewer Agent - Reviews and improves code
reviewer_agent = autogen.AssistantAgent(
    name="CodeReviewer",
    llm_config=llm_config,
    system_message="""You are a senior code reviewer and Python expert.

RESPONSIBILITIES:
- Review code for correctness, efficiency, and best practices
- Suggest improvements to code quality
- Ensure code is well-documented and readable
- Check for potential bugs or edge cases
- Validate that code matches the user's request

Provide constructive feedback and specific suggestions for improvement."""
)

# 4. User Proxy Agent
user_proxy = autogen.UserProxyAgent(
    name="UserProxy",
    human_input_mode="ALWAYS",
    max_consecutive_auto_reply=5,
    code_execution_config={
        "work_dir": OUTPUT_DIR,
        "use_docker": False,
        "timeout": 60,
    },
    system_message="""You are the User Interface Agent.

ROLE:
- Collect user requests and requirements
- Coordinate between user and other agents
- Ensure requests are clear and complete
- Facilitate the conversation flow
- Keep the user informed of progress

When the user makes a request:
1. Clarify if needed
2. Coordinate with the CoderAgent to generate code
3. Facilitate code review and execution
4. Present results to the user"""
)


# ------------------------ Main Execution ------------------------ #
def create_analysis_chat():
    """Create a group chat for collaborative analysis."""

    # Load data context
    df, report_content, data_summary = load_data_context()

    if df is None:
        print("[ERROR] Cannot load CSV data. Please ensure Input/input.csv exists.")
        return

    print("\n" + "=" * 70)
    print("ADVANCED AUTOGEN CSV ANALYSIS SYSTEM")
    print("=" * 70)
    print(f"\n[OK] Loaded CSV: {CSV_FILE}")
    print(f"  - Shape: {df.shape}")
    print(f"  - Columns: {len(df.columns)}")
    print(f"  - Numeric columns: {len(df.select_dtypes(include=['number']).columns)}")
    print(f"  - Categorical columns: {len(df.select_dtypes(include=['object', 'category']).columns)}")
    print("\n" + "=" * 70)
    print("\nAvailable agents:")
    print("  • CoderAgent - Generates and executes Python code")
    print("  • DataAnalyst - Provides analysis strategy and insights")
    print("  • CodeReviewer - Reviews and improves code quality")
    print("\n" + "=" * 70)

    # Create group chat
    groupchat = autogen.GroupChat(
        agents=[user_proxy, coder_agent, analyst_agent, reviewer_agent],
        messages=[],
        max_round=10
    )

    manager = autogen.GroupChatManager(
        groupchat=groupchat,
        llm_config=llm_config
    )

    # Initial context message
    context_msg = f"""
WELCOME TO THE CSV ANALYSIS SYSTEM!

CSV CONTEXT:
- File: {CSV_FILE}
- Shape: {df.shape}
- Columns: {', '.join(df.columns[:5])}{'...' if len(df.columns) > 5 else ''}
- Numeric columns: {', '.join(df.select_dtypes(include=['number']).columns)}
- Categorical columns: {', '.join(df.select_dtypes(include=['object', 'category']).columns)}

METADATA PREVIEW:
{report_content[:1000] if report_content else 'No metadata available'}...

AVAILABLE ACTIONS:
1. Data exploration and summarization
2. Statistical analysis
3. Data visualization (plots, charts)
4. Data cleaning and preprocessing
5. Filtering and subsetting
6. Correlation analysis
7. Grouping and aggregation
8. Export results

Please enter your analysis request:
"""

    return manager, context_msg


def interactive_mode():
    """Run in interactive mode."""
    manager, context_msg = create_analysis_chat()

    if manager is None:
        return

    print(context_msg)

    while True:
        try:
            user_input = input("\n\n>>> Your request (or 'exit' to quit): ")

            if user_input.lower() in ['exit', 'quit', 'q']:
                print("\n[OK] Goodbye!")
                break

            if not user_input.strip():
                print("[INFO] Please enter a valid request.")
                continue

            # Start the group chat
            print("\n[INFO] Starting analysis...\n")
            print("-" * 70)

            user_proxy.initiate_chat(
                manager,
                message=f"{context_msg}\n\nUSER REQUEST: {user_input}\n\nPlease proceed with the analysis."
            )

            print("-" * 70)
            print("\n[OK] Analysis complete! Ask for another analysis or 'exit' to quit.")

        except KeyboardInterrupt:
            print("\n\n[OK] Interrupted. Goodbye!")
            break
        except Exception as e:
            print(f"\n[ERROR] {e}")
            import traceback
            traceback.print_exc()


if __name__ == "__main__":
    interactive_mode()